// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PizzaGo.Data;

#nullable disable

namespace PizzaGo.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260102183342_SeedPizzasData")]
    partial class SeedPizzasData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PizzaGo.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Traditional Italian pizza with tomato sauce, fresh mozzarella and basil.",
                            ImageUrl = "",
                            Name = "Margarita",
                            Price = 10.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Classic American favorite with spicy pepperoni slices and extra mozarella.",
                            ImageUrl = "",
                            Name = "Pepperoni",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "A rich blend of Parmesan, Gorgonzola, Cheddar, and Mozarella.",
                            ImageUrl = "",
                            Name = "Four Cheese",
                            Price = 13.50m
                        },
                        new
                        {
                            Id = 4,
                            Description = "The controversial classic with juicy pineapple, ham, and tomato sauce.",
                            ImageUrl = "",
                            Name = "Hawaiian",
                            Price = 11.50m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Grilled chicken, red onions, and smoky BBQ sauce instead of tomato base.",
                            ImageUrl = "",
                            Name = "BBQ Chicken",
                            Price = 14.00m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Loaded with fresh bell peppers, mushrooms, olives, and red onions.",
                            ImageUrl = "",
                            Name = "Vegetarian",
                            Price = 11.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
