// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PizzaGo.Data;

#nullable disable

namespace PizzaGo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260113135613_FixPizza6DescriptionOnly")]
    partial class FixPizza6DescriptionOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PizzaGo.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PizzaGo.Models.OrderDetail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("PizzaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PizzaId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("PizzaGo.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A hearty pizza loaded with ground beef and extra melted mozzarella on a thick crust.",
                            ImageUrl = "/images/pizzas/foad-roshan-nDlXtnzsD5o-unsplash.jpg",
                            Name = "Cheesy Meat",
                            Price = 13.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sweet pineapple chunks, savory ham, and crispy bacon bits over a rich tomato base.",
                            ImageUrl = "/images/pizzas/heather-barnes-YKvGUO4Zb7Y-unsplash.jpg",
                            Name = "Tropical Feast",
                            Price = 12.50m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Juicy grilled chicken pieces mixed with fresh green bell peppers and aromatic herbs.",
                            ImageUrl = "/images/pizzas/rizwan-ahmed-E38gYohvCGs-unsplash.jpg",
                            Name = "Chicken & Pepper",
                            Price = 14.00m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Traditional thin-crust pizza topped with generous layers of spicy pepperoni and cheese.",
                            ImageUrl = "/images/pizzas/pexels-polina-tankilevitch-4109085.jpg",
                            Name = "Classic Pepperoni",
                            Price = 11.99m
                        },
                        new
                        {
                            Id = 5,
                            Description = "For those who like it hot: premium spicy salami with double cheese and a smokey finish.",
                            ImageUrl = "/images/pizzas/foad-roshan-JOYjHvOTFJQ-unsplash.jpg",
                            Name = "Spicy Salami",
                            Price = 13.50m
                        },
                        new
                        {
                            Id = 6,
                            Description = "A rustic mix of savory salami, fresh mushrooms, and black olives.",
                            ImageUrl = "/images/pizzas/pexels-roman-odintsov-5903178.jpg",
                            Name = "Hunter's Pizza",
                            Price = 12.00m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Savory beef slices paired with forest mushrooms and creamy mozzarella cheese.",
                            ImageUrl = "/images/pizzas/foad-roshan-QRUFgHHd2F8-unsplash.jpg",
                            Name = "Beef & Mushroom",
                            Price = 14.50m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Fresh basil leaves and crispy pepperoni slices on a zesty tomato and garlic sauce.",
                            ImageUrl = "/images/pizzas/mike-cox-dlctifSsn_8-unsplash.jpg",
                            Name = "Pepperoni Basil",
                            Price = 13.00m
                        });
                });

            modelBuilder.Entity("PizzaGo.Models.OrderDetail", b =>
                {
                    b.HasOne("PizzaGo.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaGo.Models.Pizza", "Pizza")
                        .WithMany()
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Pizza");
                });

            modelBuilder.Entity("PizzaGo.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
